experiment_name: "proxy_former_niah_dmodel_512_min_chunk_64_train_seq_len_8k"

# Model configuration
ar_model:
  module: "src.models.architectures.llm.proxy_former_llm"
  class_name: "ArLLM"

  d_model: 512
  d_attn_scale: 1
  d_history: 64
  d_head: 64
  n_layers: 10
  
  
  share_proxy_gen_transformer: true
  

  dropout: 0.0

  history_enable: true

  rope_enable: true
  chunk_size: 64
  layer_compress_ratio: [64, 64, 64, 64, 64, 64, 64, 64, 64, 64]

  weights:
    license: "cc-by-nc-sa-4.0"
    auto_download: true

    source: "hf"  # hf, url 
    
    hf:
      repo_id: "simonCat/proxy_former"
      subpath: "proxy_former_niah_dmodel_512_min_chunk_64_train_seq_len_8k" # 仓库内的子目录或单文件路径
      is_folder: true                       # true: 下载整个子目录; false: 下载单文件
      use_mirror: false                      # 是否开启镜像加速
      mirror_url: "https://hf-mirror.com"

    # 如果 is_folder 为 false，可填入单文件的 sha256；若为 true 则设为 null
    sha256: null
    
########################################
tokenizer:
  module: "src.tokenizer.gpt2_tokenizer"
  class_name: "get_tokenizer_gpt2"

  vocab_size: 50257

  hf_cache_path: "hf_cache/"
  tokenizer_dir: "./out/tokenizer/gpt2/"
  model_type: bpe  # unigram or bpe
  num_processes: 1
  content_column: "content"

########################################
data:
  module: "src.dataset.data_loader_passkey_retrieval"
  class_name: "data_loader_passkey_retrieval"

  dataset_dir: "./out/dataset_cache/wikitext-103-v1/download/"

  dataset_path: "Salesforce/wikitext"
  dataset_name: "wikitext-103-v1"

  train_bin: "./out/dataset_cache/wikitext-103-v1/train.bin"
  eval_bin: "./out/dataset_cache/wikitext-103-v1/eval.bin"

  num_workers: 1
  num_passkeys: 1
  history_len: 256

########################################
# Training configuration
training:
  module: "src.trainer.train_ar"
  func: "train"

  
  optimizer: "mano" # adamw or AdamW8bit
  learning_rate: 3.0e-4
  weight_decay: 0.01
  beta1: 0.9
  beta2: 0.98
  grad_clip: 1.0

  lr_scheduler:
    enable: true
    
    type: "warmup_then_cosine" #"cosine"
    
    warmup_ratio: 0.06

    min_lr: 1.0e-5

  # Training loop
  num_train_epochs: 5

  # stride: 512
  train_ratio: 1.0 
  
  gradient_accumulation: 16  # 梯度累积后的等效反向传播

  #  BATCH_SIZE
  per_device_train_batch_size: 256
  
  # Logging and saving
  logging_steps: 10 # Log every accumulated step
  save_tokens_ratio: 0.2 # SAVE_MODLE_STEPS
  
  
  train_stage: "ar" # "ar" or "fm"
  

eval:
  module: "src.evaluator.eval_niah"
  func: "evaluate"

  eval_ratio: 1.0 
  per_device_eval_batch_size: 1

########################################
# Profile
profiler:
  enable: false
  log_dir: "out/profiler/"
  wait: 16  # wait: 等待1步
  warmup: 16  # warmup: 预热1步
  active: 16  # active: 真正分析的3步
  repeat: 4  # repeat: 重复2次这个周期    
########################################


# Hardware
hardware:
  device: "cuda"
  autocast: true # true or false
  compile: true # true or false
  auto_eager: true # true or false
